#!/bin/bash

action-set previous="$(apt-cache policy drone)"

wget -O /tmp/drone.deb http://downloads.drone.io/master/drone.deb

dpkg -i /tmp/drone.deb

action-set installed="$(apt-cache policy drone)"
