- hosts: all
  gather_facts: true
  vars:
      mysql_enabled: 0
  tasks:
    - include: config-changed.yaml
      tags:
        - config-changed

    - name: Restart Drone
      service: name=drone state=restarted
      tags:
        - start
        - config-changed

    - name: Stop Drone
      service: name=drone state=stopped
      tags:
        - stop

    - name: External Database Configuration
      include: db-relation-changed.yaml
      tags:
        - db-relation-changed

    - name: render config
      template: src=../templates/drone.toml dest=/etc/drone/drone.toml
      tags:
        - db-relation-changed
        - config-changed

